//
//  SasayakiSettingsView.swift
//  Hoshi Reader
//
//  Copyright © 2026 Manhhao.
//  SPDX-License-Identifier: GPL-3.0-or-later
//

import SwiftUI

struct SasayakiSettingsView: View {
    @Environment(UserConfig.self) var userConfig
    var body: some View {
        @Bindable var userConfig = userConfig
        List {
            Section {
                Toggle("Enable", isOn: $userConfig.enableSasayaki)
            } footer: {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Listen to audiobooks and read along with highlighted text.")
                    if userConfig.enableSasayaki {
                        Text("An **.srt** file generated by **[SubPlz](https://github.com/kanjieater/SubPlz)** and an audiobook (**.mp3**/**.m4b**) are required.")
                        Text("Long press a book and choose **Match**.")
                        Text("Choose the **.srt** and press **Match**. Matching only has to be done once.")
                        Text("You can now open the book and choose **Sasayaki** from the context menu.")
                        Text("Load the audiobook and press play, lines will be highlighted as the audiobook plays.")
                        Text("**[More...](https://github.com/Manhhao/Hoshi-Reader/blob/main/SASAYAKI.md)**")
                    }
                }
            }
            
            if userConfig.enableSasayaki {
                Section("Settings") {
                    Toggle("Show Sasayaki Toggle", isOn: $userConfig.readerShowSasayakiToggle)
                    Toggle("Auto-Scroll", isOn: $userConfig.sasayakiAutoScroll)
                    Toggle("Auto-Pause on Lookup", isOn: $userConfig.sasayakiAutoPause)
                }
                
                Section {
                    Toggle("Show Skip (±15s) Controls", isOn: $userConfig.sasayakiSkipControls)
                } header: {
                    Text("Command Center")
                } footer: {
                    Text("Skip Controls will replace Next/Previous Cue controls as media controls.")
                }
                
                Section("Light Theme") {
                    ColorPicker("Text Color", selection: $userConfig.sasayakiTextColor)
                    ColorPicker("Background Color", selection: $userConfig.sasayakiBackgroundColor)
                }
                
                Section("Dark Theme") {
                    ColorPicker("Text Color", selection: $userConfig.sasayakiDarkTextColor)
                    ColorPicker("Background Color", selection: $userConfig.sasayakiDarkBackgroundColor)
                }
                
                if userConfig.enableSync {
                    Section("Sync") {
                        Toggle("ッツ Sync", isOn: $userConfig.sasayakiEnableSync)
                    }
                }
            }
        }
        .navigationTitle("Sasayaki")
    }
}
