//
//  SasayakiSettingsView.swift
//  Hoshi Reader
//
//  Copyright © 2026 Manhhao.
//  SPDX-License-Identifier: GPL-3.0-or-later
//

import SwiftUI

struct SasayakiSettingsView: View {
    @Environment(UserConfig.self) var userConfig
    var body: some View {
        @Bindable var userConfig = userConfig
        NativeSettingsForm {
            NativeSettingsSectionCard {
                Text("Sasayaki")
            } content: {
                NativeSettingsToggle("Enable", isOn: $userConfig.enableSasayaki)
            } footer: {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Listen to audiobooks and read along with highlighted text.")
                    if userConfig.enableSasayaki {
                        Text("An **.srt** file generated by **[SubPlz](https://github.com/kanjieater/SubPlz)** and an audiobook (**.mp3**/**.m4b**) are required.")
                        Text("Long press a book and choose **Match**.")
                        Text("Choose the **.srt** and press **Match**. Matching only has to be done once.")
                        Text("You can now open the book and choose **Sasayaki** from the context menu.")
                        Text("Load the audiobook and press play, lines will be highlighted as the audiobook plays.")
                        Text("**[More...](https://github.com/Manhhao/Hoshi-Reader/blob/main/SASAYAKI.md)**")
                    }
                }
            }

            if userConfig.enableSasayaki {
                NativeSettingsSectionCard("Settings") {
                    NativeSettingsToggle("Show Sasayaki Toggle", isOn: $userConfig.readerShowSasayakiToggle)
                    NativeSettingsSeparator()
                    NativeSettingsToggle("Auto-Scroll", isOn: $userConfig.sasayakiAutoScroll)
                    NativeSettingsSeparator()
                    NativeSettingsToggle("Auto-Pause on Lookup", isOn: $userConfig.sasayakiAutoPause)
                }

                NativeSettingsSectionCard {
                    Text("Command Center")
                } content: {
                    NativeSettingsToggle("Show Skip (±15s) Controls", isOn: $userConfig.sasayakiSkipControls)
                } footer: {
                    Text("Skip Controls will replace Next/Previous Cue controls as media controls.")
                }

                NativeSettingsSectionCard("Light Theme") {
                    NativeSettingsRow("Text Color") {
                        ColorPicker("", selection: $userConfig.sasayakiTextColor)
                            .labelsHidden()
                    }
                    NativeSettingsSeparator()
                    NativeSettingsRow("Background Color") {
                        ColorPicker("", selection: $userConfig.sasayakiBackgroundColor)
                            .labelsHidden()
                    }
                }

                NativeSettingsSectionCard("Dark Theme") {
                    NativeSettingsRow("Text Color") {
                        ColorPicker("", selection: $userConfig.sasayakiDarkTextColor)
                            .labelsHidden()
                    }
                    NativeSettingsSeparator()
                    NativeSettingsRow("Background Color") {
                        ColorPicker("", selection: $userConfig.sasayakiDarkBackgroundColor)
                            .labelsHidden()
                    }
                }

                if userConfig.enableSync {
                    NativeSettingsSectionCard("Sync") {
                        NativeSettingsToggle("ッツ Sync", isOn: $userConfig.sasayakiEnableSync)
                    }
                }
            }
        }
        .navigationTitle("Sasayaki")
    }
}
